version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    
  nginx:
    build:
      context: ./nginx
    ports:
      - "8081:8080"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
